### ISSUE TITLE
Trouble with login with the app and the length of the challenge

### ISSUE THREAD

**Issue by basvandervlies** [SURFnet/tiqr-client-ios#39]
I am using PrivacyIdea TIQR token and with suite `OCRA-1:HOTP-SHA1-6:QN10`. Which means I generate a 10 bits random value:
```
QH10-­‐S     –     the     input     for     the     challenge     (in     this    case    a    10-­‐digit    hexadecimal    value    represented    as    a    string)    and    the    size    of    the    session    data    (in    this    case    the    default    value    of  64 bytes
```

I encounter problems when login with the TIQR token after a successful enrollment.  I noticed that the authentication process was flaky. Sometimes it worked and other times it showed  me that I entered the wrong PIN code.

After some debugging I encounter that values equal or above `2147483648` does not work.  So the generated string is stored in a int to the power 31 `(2^31)`. Is this a correct assumption?

**Comment by basvandervlies** [comment]
The strange part if  change the ORCA suite to use a shorter length:
 * `OCRA-1:HOTP-SHA1-6:QN08`

Is does not work at all.

**Comment by 7hommay** [comment]
When specifying a numerical value (string) for the challenge, the client converts the value to a hexadecimal (string). This conversion was limited to signed 32 bit values due to the format specifier that was used. So your assumption was correct. I've opened a PR to expand the conversion to 64 bit unsigned values. Hopefully that resolves the issue.

**Comment by basvandervlies** [comment]
@7hommay thanks
